EVALUATE
{
--Las salidas son Ud que figuran en negativo en la tabla origen------
VAR _salidas =      CALCULATE(
                        SUM( factPedidos[ud] )* -1,
                        factPedidos[ud] < 0
                    )

--Creación de tabla virtual con meses y ud acumuladas----------------
VAR _tabla =    ADDCOLUMNS(
                    SUMMARIZE(
                        dimCalendario,
                        dimCalendario[AñoMes]
                    ),
                    "@Ud Acum",
                    CALCULATE(
                        VAR _diaMax = MAX(dimCalendario[fecha])
                        RETURN
                        CALCULATE(
                            SUM(factPedidos[ud]),
                            dimCalendario[fecha] <= _diaMax
                        )
                    )
                )

--Determinación del Nº de meses que tienen datos---------------------
VAR _conDat =   FILTER(
                    _tabla,
                    [@Ud Acum] > 0
                )
VAR _nMeses =   COUNTROWS(_conDat)

--Creación del promedio sobre las cifras acumuladas------------------
VAR _totAcum =  SUMX(_tabla, [@Ud Acum])
VAR _promAcum = DIVIDE(_totAcum, _nMeses)

--Cálculo final------------------------------------------------------
VAR _result =   DIVIDE(_salidas, _promAcum)

RETURN          _result
}