-- COLUMNAS CALCULADAS -- 

22-ColumnaCiudades =
RELATED(Country[Province])


23-ColumnaCondicional = 
IF( Sales[Country] = "Francia",
    RELATED(Country[])
)


24-ColumnaCondicionalDoble =
    IF(
        AND(
        Sales[Country] = "Grecia" , Sales[Date] = 2016
    ) , RELATED(Country[Province]),
    BLANK()
    )


25-ImpuestosPorVentas =
LOOKUPVALUE(
    'Country Tax'[TAX],
    'Country Tax'[Country],
    'Country2'[Country]
)


26-ImpuestosporVentasAlemania = 
IF(
    'Country2'[Country] = "Germany",
    LOOKUPVALUE(
        'Country Tax'[TAX],
        'Country Tax'[Country],
        'Country2'[Country]
    ), 
    BLANK()
)


27-VentasAlemania-Canada = 
IF(
    Country2[Country] IN {"Germany" , "Canada"}
    LOOKUPVALUE(
        "CountryTax[Tax]",
        "CountryTax[Country]",
        "Country2[Country]"
    ),
    BLANK()
)


28-CashFlowBajo = 
CALCULATE(
    SUM(CashFlow[Movement],
    FILTER(
        Cashflow,
        CashFlow[Reg] <= EARLIER(
            CashFlow[Reg]
        )
    )
    )
)


29-CashFlowTime = 
CALCULATE(
    SUM(CashFlow[Movement]),
    FILTER(
        CashFlow,
        CashFlow[DATE] <= EARLIER(
            CashFlow[DATE]
        )
    )
)



    -- MEDIDAS --


30-MedidaPorTiempo =
CALCULATE(
    SUM(Sales[Sales]),
    FILTER(
        ALL(Sales),
        RELATED(Calendario[Año]) = 2014
    )
)


31-SumaPorTiempo2 =
CALCULATE(
    SUM(Sales[Sales]),
    FILTER(
        ALL(Sales),
        Sales[Date] <= MAX(Sales[Date])
    )
)


32-ConteoPorVentasyPais = 
CALCULATE(
    COUNT(Sales[Sales]),
    Sales[Country] = "Mexico"
)


33-ConteoVentasSinFiltros = 
CALCULATE(
    COUNT(Sales[Sales]),
    FILTER(
        ALL(Sales),
        Sales[Country] = "Canada")
)



34-ConteoValores = 
CALCULATE(
    COUNT(Sales[Sales]),
    FILTER(
        Sales,
        Sales[Country] = "Canada" && Sales[Sales] > 1000 -- AND() 
    )   
)


35-PaisesDistintos = 
DISTINCTCOUNT(Sales[Country])


36-PaisesDiferentesSinFiltros = 
CALCULATE(
    DISTINCTCOUNT(
        Sales[Country]),
        ALL(Sales)
)


37-ContarProductosVendidos = 
COUNTX(
    FILTER(
        ALL(Sales),
        RELATED(Product[Product]) = Sales[Product]
    ),
    Sales[Sales]
)


38-NumeroProductosVendidos = 
CALCULATE(
    DISTINCTCOUNTNOBLANK(Sales[Product]),
    CROSSFILTER(
        Product[Product],
        Sales[Product],
        Both
    )
)


39-ValorUnicoRelacionandoTablasSinRelacion = 
CALCULATE(
    DISTINCTCOUNTNOBLANK(Sales[Product]),
    TREATAS(
        Country3,
        CountryTax[Country]
    )
)


40-ProductosPorCategoria = 
SUMMARIZE(
    Sales,
    Sales[Product],
    "Numero de Ventas", COUNT(
        Sales[Product]
    )
)


41-ContaValores = 
SUMMARIZE(
    Sales,
    Sales[Product],
    "Numero de Ventas", DISTINCTCOUNT(  -- Es el ejemplo del libro pero no tiene logica.
        Sales[Product]
    )
)


42-NumeroVentasAlemania = 
CALCULATE(
    COUNTROWS(Sales),
    Sales[Country] = "Germany"
)


43-ContarSinEfectosdeFiltro = 
CALCULATE(
    COUNTROWS(Sales),
    FILTER(
        ALL(Sales),
        Sales[Country] = "Germany"
    )
)


44-Subtotal por categoria = 
SUMMARIZECOLUMNS(
    ROLLUPADDISSUBTOTAL(
        Sales[Sector], 
        "Subtotal",
        Sales
    ),
    Salesman[Salesman],
    "Ventas", SUM(Sales[Sales])
)







