Calendario = 
ADDCOLUMNS(
    CALENDAR(
        
        MIN(Sales[Date]),
        MAX(Sales[Date])),

        "Año", YEAR([Date]),
        "Mes", MONTH([Date]),
        "Trimestre", "Trim - " & QUARTER([Date]),
        "Día", DAY([Date]),
        "Dia de la semana", WEEKDAY([Date]),
        "Nombre del mes", FORMAT([Date],"MMMM"),
        "Trimestre-letras", 
            SWITCH(
                QUARTER([Date]), 
                1, "Primero",
                2, "Segundo",
                3, "Tercero",
                4, "Cuarto",
                 "Fallo en trimestre")
)


--------------------------------------------

dimFechasCALENDAR = 


CALENDAR (
    DATE( YEAR( MIN( factPedidos[fechaPedido] ) ), 1, 1),
    DATE( YEAR( MAX( factPedidos[fechaPedido] ) ), 12, 31)
)


  
--------------------------------------------



  
  
dimFechasCALENDARAUTO = 
CALENDARAUTO ()


    -> no es nada recomedable, la posibilidad de que te genere errores y amplie el espacio del modelo es alta.
